"""baseline schema

Revision ID: 3fd6b0ffe1e8
Revises: 
Create Date: 2026-09-10 11:30:37.314246

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3fd6b0ffe1e8'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asr_provider',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('keywords', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('end_of_turn_confidence', sa.Float(), nullable=True),
    sa.Column('end_of_turn_timeout', sa.Integer(), nullable=True),
    sa.Column('min_speech_duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asr_provider_id'), 'asr_provider', ['id'], unique=False)
    op.create_table('catalog_prompts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('prompt_text', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_catalog_prompts_id'), 'catalog_prompts', ['id'], unique=False)
    op.create_table('catalog_providers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stage', 'name', name='uq_catalog_provider_stage_name')
    )
    op.create_index(op.f('ix_catalog_providers_id'), 'catalog_providers', ['id'], unique=False)
    op.create_table('llm_provider',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('mcp_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_provider_id'), 'llm_provider', ['id'], unique=False)
    op.create_table('tts_provider',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('speaker_audio', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tts_provider_id'), 'tts_provider', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('catalog_languages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['catalog_providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'name', name='uq_catalog_language_provider_name')
    )
    op.create_index(op.f('ix_catalog_languages_id'), 'catalog_languages', ['id'], unique=False)
    op.create_table('catalog_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['catalog_providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'value', name='uq_catalog_model_provider_value')
    )
    op.create_index(op.f('ix_catalog_models_id'), 'catalog_models', ['id'], unique=False)
    op.create_table('custom_voice_agents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_username', sa.String(), nullable=False),
    sa.Column('asr_provider_name', sa.String(), nullable=True),
    sa.Column('llm_provider_name', sa.String(), nullable=True),
    sa.Column('tts_provider_name', sa.String(), nullable=True),
    sa.Column('asr_id', sa.Integer(), nullable=True),
    sa.Column('llm_id', sa.Integer(), nullable=True),
    sa.Column('tts_id', sa.Integer(), nullable=True),
    sa.Column('greeting_message', sa.String(), nullable=True),
    sa.Column('end_call_message', sa.String(), nullable=True),
    sa.Column('respose_audio_delay', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['asr_id'], ['asr_provider.id'], ),
    sa.ForeignKeyConstraint(['llm_id'], ['llm_provider.id'], ),
    sa.ForeignKeyConstraint(['tts_id'], ['tts_provider.id'], ),
    sa.ForeignKeyConstraint(['user_username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_custom_voice_agents_id'), 'custom_voice_agents', ['id'], unique=False)
    op.create_table('call_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('agent_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['custom_voice_agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_history_id'), 'call_history', ['id'], unique=False)
    op.create_table('catalog_voices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['catalog_models.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['catalog_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_voices_id'), 'catalog_voices', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalog_voices_id'), table_name='catalog_voices')
    op.drop_table('catalog_voices')
    op.drop_index(op.f('ix_call_history_id'), table_name='call_history')
    op.drop_table('call_history')
    op.drop_index(op.f('ix_custom_voice_agents_id'), table_name='custom_voice_agents')
    op.drop_table('custom_voice_agents')
    op.drop_index(op.f('ix_catalog_models_id'), table_name='catalog_models')
    op.drop_table('catalog_models')
    op.drop_index(op.f('ix_catalog_languages_id'), table_name='catalog_languages')
    op.drop_table('catalog_languages')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tts_provider_id'), table_name='tts_provider')
    op.drop_table('tts_provider')
    op.drop_index(op.f('ix_llm_provider_id'), table_name='llm_provider')
    op.drop_table('llm_provider')
    op.drop_index(op.f('ix_catalog_providers_id'), table_name='catalog_providers')
    op.drop_table('catalog_providers')
    op.drop_index(op.f('ix_catalog_prompts_id'), table_name='catalog_prompts')
    op.drop_table('catalog_prompts')
    op.drop_index(op.f('ix_asr_provider_id'), table_name='asr_provider')
    op.drop_table('asr_provider')
    # ### end Alembic commands ###
