"""add tts_voice_references table

Revision ID: 7c983ba172dc
Revises: 3fd6b0ffe1e8
Create Date: 2026-09-10 17:42:37.235412

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7c983ba172dc'
down_revision: str | None = '3fd6b0ffe1e8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tts_voice_references',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('audio_path', sa.String(), nullable=False),
    sa.Column('transcript', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tts_voice_references_id'), 'tts_voice_references', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tts_voice_references_id'), table_name='tts_voice_references')
    op.drop_table('tts_voice_references')
    # ### end Alembic commands ###
